sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - npm install cheerio@0.22.0 –save
  - npm install hexo-renderer-pug hexo-renderer-stylus --save
  - npm un hexo-renderer-marked --save
  - npm un hexo-math --save
  - npm i @upupming/hexo-renderer-markdown-it-plus --save
  - hexo clean #清除旧的内容
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public