# Main menu navigation
# ---------------
# format: xxx: 連結 || icon
# sub-menu
# xxx || icon:
#   xxx || 連結 || icon



# 导航
menu:
  首页: / || fas fa-home
  归档: /archives/ || fa fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

# Favicon
# ---------------
favicon: /favicon.ico


# A simple 404 page
error_404:
  enable: true
  subtitle: "日常迷路……"
  background: 

# Post info settings
# ---------------
avatar:
  img: /img/avatar.jpeg
  effect: false # 頭像會一直轉圈

# 加載動畫 Loading Animation
preloader: true


# 主頁subtitle
# 打字效果
subtitle:
  enable: true
  source: false
  # (如果有英文逗號' , '，請使用轉義字符 &#44;)
  sub:
    - 唯有尽力自持，方不致癫狂
    - 总之岁月漫长，然而值得等待
    - 我来，我见，我征服
    - 生活的最佳状态是冷冷清清的风风火火
    - 我要努力，至少不给未来得自己回忆时，留下任何遗憾
    - 过去的就把它忘了重新开始
    - 时间会给你想要的一切
    - 我想活的明媚如阳光，照射给每一个人
    - 低头哭过别忘了抬头继续走
    - 所有的不快乐都是因为想太多
    - 梦里能到达的地方，脚步也能到达
    - 一个人真正的强大，是能坦然理解所有生命里的世事无常
    - 我相信，路总会有平坦的一面
    - 人生不就是，先进攻再撤退
    - 这一秒不放弃，下一秒就会有希望
    - 男人再苦也不怕心中有梦闯天下
    - 立志在坚不在锐，成功在久不在速
    - 任何不快乐的时光都是浪费
    - 有些事不要逞强，有些人不必勉强
    - 不要让未来的你瞧不起此刻的你
    - 人就活一次，酸甜苦辣咱得笑着
    - 有时间去嫉妒为什么不去奋斗
    - 多么美妙的生活，值得我们好好珍惜
    - 猛兽总是独行，牛羊才成群结队
    - 醉卧沙场君莫笑，古来长生有几何
    - 犹豫久了，勇气会消失


# Highlight theme
# ---------------
highlight_theme: light # default / darker / pale night / light / ocean
highlight_copy: true #代碼複製按鈕
highlight_lang: false #代碼語言顯示
highlight_shrink: false # true 全部代碼框不展開，需點擊 '>' 打開 / false 代碼框展開，有'>'點擊按鈕 | none 代碼框展開，不顯示 '>' 按鈕
code_word_wrap: false


# 主頁文章COVER顯示位置
# 三個值可配置 left , right , both
# left(全部圖片顯示在左邊)，right(全部圖片顯示在右邊)，both(左右左右順序顯示)
index_post_cover: both


# aside
# ---------------
aside:
  enable: true
  hide: false
  button: true
  mobile: false # 手機頁面（ 顯示寬度 < 768px ）是否顯示aside內容
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Github
      link: https://github.com/KingCraigSong
  card_announcement:
    enable: false
    content: This is my Blog
  card_recent_post:
    enable: false
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories:
    enable: false
    limit: 8 # if set 0 will show all
    expand: true # none/true/false
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: true
  card_archives:
    enable: false
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true

toc:
  enable: true
  number: true
  style_simple: true


#####     Footer Settings    ####
# ------------------------------------
footer:
  owner:
    enable: true
    since: 2020
  custom_text: <a href="#"><span>ICP备：进行中</span></a>

post_copyright:
  enable: false

related_post:
  enable: false
  limit: 6 # 顯示推薦文章數目
  date_type: created # or created or updated 文章日期顯示創建日或者更新日


sharejs:
  enable: true
  sites: wechat,qq  #想要顯示的內容

# Local search
# Please see doc for more details: https://jerryc.me/posts/21cfbf15/#本地搜索
# ---------------
# local_search:
#   path: search.xml
#   field: post
#   format: html
#   limit: 10000
#   enable: true
#   labels:
#     input_placeholder: Search for Posts
#     hits_empty: "We didn't find any results for the search: ${query}" # if there are no result

local_search:
  enable: true

search:
  path: search.xml
  field: post
  content: true


canvas_fluttering_ribbon:
  enable: true
  mobile: false # false 手機端不顯示 true 手機端顯示


# 大图预览
fancybox: true
# Disable Baidu transformation on mobile devices (禁止百度轉碼)
disable_baidu_transformation: true



# # the banner image of index
# index_img: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/top_img/index.jpg
# the banner image of index
index_img: 'linear-gradient(20deg, #0062be, #925696, #cc426e, #fb0347)'

# if the banner of page not setting,it will show the top_img
default_top_img: 'linear-gradient(135deg, rgba(109,179,242,1) 0%,rgba(84,163,238,0.93) 47%,rgba(30,105,222,0.86) 100%)'

# the default cover of the post
cover:
  # display the cover or not (是否顯示文章封面)
  index_enable: true
  aside_enable: true
  archives_enable: true
  # the position of cover in home page (封面顯示的位置)
  # left/right/both
  position: both
  # When cover is not set, the default cover is displayed (當沒有設置cover時，默認的封面顯示)
  default_cover: 
    - 'linear-gradient(#e66465, #9198e5)'
    - 'linear-gradient(135deg, rgba(109,179,242,1) 0%,rgba(84,163,238,0.93) 47%,rgba(30,105,222,0.86) 100%)'
    - 'linear-gradient(20deg, #0062be, #925696, #cc426e, #fb0347)'

# the banner image of archive page
archive_img: 'linear-gradient(#e66465, #9198e5)'

# the banner image of tag page
tag_img: 'linear-gradient(135deg, rgba(109,179,242,1) 0%,rgba(84,163,238,0.93) 47%,rgba(30,105,222,0.86) 100%)'
tag_per_img: 

# the banner image of category page
category_img: 'linear-gradient(#e66465, #9198e5)'
category_per_img: 

# 打賞按鈕
reward:
  enable: false
  QR_code:
    - itemlist:
        img: /img/wechat.png
        text: wechat
    - itemlist:
        img: /img/alipay.png
        text: alipay

# 美化post頁顯示
post_beautify:
  enable: false
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"

# busuanzi count for PV / UV in site
# 訪問人數
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 網頁開通時間
# 格式: 月/日/年 時間
# 也可以寫成 年/月/日 時間
runtimeshow:
  enable: false
  start_date: 1/1/2020 00:00:00
  
# 網站名字字體
# 左上角網站名字 主頁居中網站名字
blog_title_font:
  font_link: https://fonts.googleapis.com/css?family=Titillium+Web #字體鏈接
  font-family: Titillium Web, PingFang SC, Hiragino Sans GB, "Microsoft YaHei", Helvetica Neue, Helvetica, Arial, sans-serif

# 水平分隔綫
hr:
  enable: false
  icon: '\f21c' #fontawesome上圖標的Unicode
  icon-top: -20px






# CDN
# 網站必須
# 可根據需要自行添加js/css
CDN_USE:
  css:
    - /css/index.css
    - https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    # - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css #fontawesomeV5_css

  js:
    - https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js #/js/third-party/jquery.min.js
    - /js/utils.js
    - /js/main.js

# CDN
# 非必要不要修改
CDN:
  #comments
  blueimp_md5: https://cdn.jsdelivr.net/npm/blueimp-md5@2.10.0/js/md5.min.js
  gitalk: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
  gitalk_css: https://cdn.jsdelivr.net/npm/gitalk/dist/gitalk.min.css
  valine: https://cdn.jsdelivr.net/npm/valine/dist/Valine.min.js

  # share
  addtoany: https://static.addtoany.com/menu/page.js
  sharejs: https://cdn.jsdelivr.net/npm/social-share.js/dist/js/social-share.min.js
  sharejs_css: https://cdn.jsdelivr.net/npm/social-share.js/dist/css/share.min.css

  mathjax: https://cdn.jsdelivr.net/npm/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  katex: https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
  katex_copytex: https://cdn.jsdelivr.net/npm/katex-copytex@latest/dist/katex-copytex.min.js
  katex_copytex_css: https://cdn.jsdelivr.net/npm/katex-copytex@latest/dist/katex-copytex.min.css

  #不蒜子計數器
  busuanzi: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

  # 背景特效
  canvas_ribbon: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/js/canvas-ribbon.js
  canvas_ribbon_piao: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/js/piao.js
  canvas_nest: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/js/canvas-nest.js

  lazyload: https://cdn.jsdelivr.net/npm/lazysizes@latest/lazysizes.min.js
  instantpage: https://cdn.jsdelivr.net/npm/instant.page@latest/instantpage.min.js

  typed: https://cdn.jsdelivr.net/npm/typed.js
  js_cookies: https://cdn.jsdelivr.net/npm/js-cookie/dist/js.cookie.min.js

  fancybox_css: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.css
  fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.js
  medium_zoom: https://cdn.jsdelivr.net/npm/medium-zoom/dist/medium-zoom.min.js

  snackbar_css: https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.css
  snackbar: https://cdn.jsdelivr.net/npm/node-snackbar/dist/snackbar.min.js

  #鼠标点击特效
  anime: https://cdn.jsdelivr.net/npm/animejs@latest/anime.min.js
  activate_power_mode: https://cdn.jsdelivr.net/npm/activate-power-mode/dist/activate-power-mode.min.js
  fireworks: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/js/fireworks.js
  click_heart: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/js/click_heart.js
  ClickShowText: https://cdn.jsdelivr.net/gh/jerryc127/butterfly_cdn@2.1.0/js/ClickShowText.js

  translate: /js/tw_cn.js